sudo: required

language: python

python:
  - "3.6"
  - "3.7-dev"

services:
  - docker

install:
  - pip install -r requirements.txt

script: python -m pytest

jobs:
  include:
    - stage: "dockerize"
    - name: dockerizer
    - if: branch = master
    - script: 
      - docker build -t flopezh/queens .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push flopezh/queens